# Generated by Django 2.2.5 on 2019-09-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_is_editor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_editor',
            new_name='editor',
        ),
    ]
